[all:vars]
yourvar= 4400

[Cisco]
sw1 ansible_host=192.168.160.132 username=cisco password=cisco ;yourvar=10
sw2 ansible_host=192.168.160.133 username=cisco password=cisco 

;[cisco:vars]
;yourvar=500

[Juniper]
sw3 ansible_host=192.168.160.134 username=cisco password=cisco 
sw4 ansible_host=192.168.160.135 username=cisco password=cisco 

;[juniper:vars]
;yourvar=1000
; [Cisco-Juniper:children]
; Cisco
; Juniper
;[Cisco-Juniper:vars]
;ourvar=3333
